# Generated by Django 2.1 on 2018-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20180809_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_weightage', models.IntegerField(choices=[(1, 'ONE'), (2, 'TWO'), (3, 'THREE'), (4, 'FOUR'), (5, 'FIVE'), (6, 'SIX'), (7, 'SEVEN')], null=True)),
                ('question_type', models.IntegerField(choices=[(1, 'TEXT'), (2, 'FILL IN THE BLANKS'), (3, 'MCQ')], null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('questions_to_attempt', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_weightage',
            field=models.IntegerField(choices=[(1, 'ONE'), (2, 'TWO'), (3, 'THREE'), (4, 'FOUR'), (5, 'FIVE'), (6, 'SIX'), (7, 'SEVEN')], null=True),
        ),
    ]
