# Generated by Django 2.1 on 2018-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20180809_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
