# Generated by Django 2.1 on 2018-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0007_auto_20180822_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestionpaper',
            name='file_path',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
