# Generated by Django 2.1 on 2018-09-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0009_generatedquestionpaper_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsplit',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchapp.Subject'),
        ),
    ]
