# Generated by Django 2.1 on 2018-09-19 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0010_subjectsplit_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='chapter_number',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='subject',
        ),
        migrations.AlterField(
            model_name='questions',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchapp.Chapter'),
        ),
    ]
