# Generated by Django 2.1 on 2018-12-11 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchapp', '0011_auto_20180919_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTestAndGenericPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('file_path', models.CharField(default=None, max_length=200, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GeneratedQuestionPaper',
            new_name='GeneratedCustomizedPaper',
        ),
    ]
