# Generated by Django 2.1 on 2019-08-12 10:02

from django.db import migrations, models
import django.db.models.deletion
import searchapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0012_auto_20181215_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE')], default='CBSE', max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', searchapp.models.MinMaxFloat(default=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.Board')),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='searchapp.Grade'),
            preserve_default=False,
        ),
    ]
